@startuml
!theme vibrant
title Sequence Diagram - Recover Password

actor User
participant RecoverPasswordScreen
participant UserRepository
participant Firebase

User -> RecoverPasswordScreen: Enters email
User -> RecoverPasswordScreen: Clicks "Recuperar Senha" button
RecoverPasswordScreen -> UserRepository: forgetPassword(email)
UserRepository -> Firebase: sendPasswordResetEmail(email)
Firebase --> UserRepository: Confirms email sent
UserRepository --> RecoverPasswordScreen: Returns success status
RecoverPasswordScreen -> User: Shows success message

@enduml
