// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL3LzdPyWa6Yc-LowvSuRf6Q1KGcCMdpA',
    appId: '1:692343760177:web:86fd53929fd46a9329fc10',
    messagingSenderId: '692343760177',
    projectId: 'usm-uerj-flutter',
    authDomain: 'usm-uerj-flutter.firebaseapp.com',
    storageBucket: 'usm-uerj-flutter.firebasestorage.app',
    measurementId: 'G-YPPEHB4XMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaAUQegg-53coW1dSy8nKCdhofYfm_Hyo',
    appId: '1:692343760177:android:022948833122496b29fc10',
    messagingSenderId: '692343760177',
    projectId: 'usm-uerj-flutter',
    storageBucket: 'usm-uerj-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTSLkUsqoFn5JDCxOphZb5kLkj69kHcQ0',
    appId: '1:692343760177:ios:c47a67735db5f86129fc10',
    messagingSenderId: '692343760177',
    projectId: 'usm-uerj-flutter',
    storageBucket: 'usm-uerj-flutter.firebasestorage.app',
    iosBundleId: 'com.danielbrown.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTSLkUsqoFn5JDCxOphZb5kLkj69kHcQ0',
    appId: '1:692343760177:ios:c47a67735db5f86129fc10',
    messagingSenderId: '692343760177',
    projectId: 'usm-uerj-flutter',
    storageBucket: 'usm-uerj-flutter.firebasestorage.app',
    iosBundleId: 'com.danielbrown.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL3LzdPyWa6Yc-LowvSuRf6Q1KGcCMdpA',
    appId: '1:692343760177:web:e51f37c46dd08a0c29fc10',
    messagingSenderId: '692343760177',
    projectId: 'usm-uerj-flutter',
    authDomain: 'usm-uerj-flutter.firebaseapp.com',
    storageBucket: 'usm-uerj-flutter.firebasestorage.app',
    measurementId: 'G-04FDRXZRD2',
  );

}